# Schema for the Inline Entity Reference module display settings.

field.widget.settings.inline_entity_form_single:
  type: mapping
  label: 'Inline entity reference display format settings'
  mapping:
    override_labels:
      type: boolean
      label: "Override labels"
    label_singular:
      type: string
      label: "Label (singular)"
    label_plural:
      type: string
      label: "Label (plural)"

field.widget.settings.inline_entity_form_multiple:
  type: mapping
  label: 'Inline entity reference display format settings'
  mapping:
    override_labels:
      type: boolean
      label: "Override labels"
    label_singular:
      type: string
      label: "Label (singular)"
    label_plural:
      type: string
      label: "Label (plural)"
    allow_new:
      type: boolean
      label: "Allow new"
    allow_existing:
      type: boolean
      label: "Allow existing"
    match_operator:
      type: string
      label: "Match operator"
